// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScrape() {
  return window['go']['main']['App']['CancelScrape']();
}

export function ScrapeDCGallery(arg1) {
  return window['go']['main']['App']['ScrapeDCGallery'](arg1);
}
