// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelScrape():Promise<boolean>;

export function ScrapeDCGallery(arg1:main.ScrapeRequest):Promise<main.ScrapeResult>;
